import type { Metadata } from "next";
import "./globals.css";
import Sidebar from "@/components/Sidebar";
import localFont from "next/font/local";
import { ReactQueryClientProvider } from "@/components/QueryClientProvider";
import { SidebarOpenProvider } from "@/components/SidebarOpenContext";
import { SourcesOpenProvider } from "@/components/SourcesOpenContext";
import MobileNavigation from "@/components/MobileNavigation";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

const fkGroteskNeue = localFont({
  src: [
    {
      path: "../public/FKGroteskNeue-Thin.otf",
      weight: "100",
      style: "normal",
    },
    {
      path: "../public/FKGroteskNeue-Light.otf",
      weight: "300",
      style: "normal",
    },
    {
      path: "../public/FKGroteskNeue-Regular.otf",
      weight: "400",
      style: "normal",
    },
    {
      path: "../public/FKGroteskNeue-Medium.otf",
      weight: "500",
      style: "normal",
    },
    {
      path: "../public/FKGroteskNeue-Bold.otf",
      weight: "700",
      style: "normal",
    },
  ],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ReactQueryClientProvider>
      <SidebarOpenProvider>
        <SourcesOpenProvider>
          <html className="dark" lang="en">
            <body
              className={`${fkGroteskNeue.className} antialiased dark:bg-contentBackgroundDark`}
            >
              <main>
                <div className="flex md:flex-row flex-col md:h-[100%] md:min-h-[100dvh] h-[100%]">
                  <div className="md:block hidden min-h-full">
                    <Sidebar />
                  </div>

                  <div className="dark:bg-mainBackgroundDark w-full md:h-auto h-[100%] flex justify-center">
                    <div className="dark:bg-contentBackgroundDark rounded-lg w-full h-full md:h-[98.5%] pb-52 top-0 bottom-0 md:border border-gray-400/10 shadow-sm right-0 left-0 my-auto md:mr-2.5">
                      {children}
                    </div>
                  </div>
                  <div className="md:md:hidden block">
                    <MobileNavigation />
                  </div>
                </div>
              </main>
            </body>
          </html>
        </SourcesOpenProvider>
      </SidebarOpenProvider>
    </ReactQueryClientProvider>
  );
}
