import type { Metadata } from "next";
import "./globals.css";
import Sidebar from "@/components/Sidebar";
import localFont from "next/font/local";
import { ReactQueryClientProvider } from "@/components/QueryClientProvider";
import { SidebarOpenProvider } from "@/components/SidebarOpenContext";
import { SourcesOpenProvider } from "@/components/SourcesOpenContext";
import MobileNavigation from "@/components/MobileNavigation";
import MobileHeader from "@/components/MobileHeader";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

const fkGroteskNeue = localFont({
  src: [
    {
      path: "../public/FKGroteskNeue-Thin.otf",
      weight: "100",
      style: "normal",
    },
    {
      path: "../public/FKGroteskNeue-Light.otf",
      weight: "300",
      style: "normal",
    },
    {
      path: "../public/FKGroteskNeue-Regular.otf",
      weight: "400",
      style: "normal",
    },
    {
      path: "../public/FKGroteskNeue-Medium.otf",
      weight: "500",
      style: "normal",
    },
    {
      path: "../public/FKGroteskNeue-Bold.otf",
      weight: "700",
      style: "normal",
    },
  ],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ReactQueryClientProvider>
      <SidebarOpenProvider>
        <SourcesOpenProvider>
          <html className="dark" lang="en">
            <body className={`${fkGroteskNeue.className} antialiased`}>
              <main>
                <div className="flex md:flex-row flex-col md:h-screen h-[calc(100dvh_-_64px_+_env(safe-area-inset-bottom,_0))]">
                  <div className="md:w-auto md:block hidden">
                    <Sidebar />
                  </div>
                  <div className="md:hidden block">
                    <MobileHeader />
                  </div>
                  <div className="dark:bg-mainBackgroundDark w-full h-full flex justify-center">
                    <div className="dark:bg-contentBackgroundDark rounded-lg w-full md:h-[98.5%] h-full pb-52 top-0 bottom-0 border border-gray-400/10 shadow-sm right-0 left-0 my-auto md:mr-2.5">
                      {children}
                    </div>
                  </div>
                  <div className="md:w-auto md:hidden block">
                    <MobileNavigation />
                  </div>
                </div>
              </main>
            </body>
          </html>
        </SourcesOpenProvider>
      </SidebarOpenProvider>
    </ReactQueryClientProvider>
  );
}
